name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]



jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci --also=dev
    - run: npm run build --if-present
    - run: npm test
    - name: Install dependencies
    - run: npm install
    env:
      API_KEY: ${{ secrets.API_KEY }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
